global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-api'
    static_configs:
      - targets: ['host.docker.internal:5001']  # Auth API running on host
remote_write:
  - url: "http://localhost:9090/api/v1/write"